<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class LgasTableSeeder extends Seeder
{
    public function run()
    {
        $statesWithLgas = [
            'Abia' => ['Aba North', 'Aba South', 'Arochukwu', 'Bende', 'Ikwuano', 'Isiala Ngwa North', 'Isiala Ngwa South', 'Isuikwuato', 'Obi Ngwa', 'Ohafia', 'Osisioma', 'Ugwunagbo', 'Ukwa East', 'Ukwa West', 'Umuahia North', 'Umuahia South', 'Umu Nneochi'],
            'Adamawa' => ['Demsa', 'Fufore', 'Ganye', 'Girei', 'Gombi', 'Guyuk', 'Hong', 'Jada', 'Lamurde', 'Madagali', 'Maiha', 'Mayo-Belwa', 'Michika', 'Mubi North', 'Mubi South', 'Numan', 'Shelleng', 'Song', 'Toungo', 'Yola North', 'Yola South'],
            'Akwa Ibom' => ['Abak', 'Eastern Obolo', 'Eket', 'Esit Eket', 'Essien Udim', 'Etim Ekpo', 'Etinan', 'Ibeno', 'Ibesikpo Asutan', 'Ibiono Ibom', 'Ika', 'Ikono', 'Ikot Abasi', 'Ikot Ekpene', 'Ini', 'Itu', 'Mbo', 'Mkpat-Enin', 'Nsit-Atai', 'Nsit-Ibom', 'Nsit-Ubium', 'Obot Akara', 'Okobo', 'Onna', 'Oron', 'Oruk Anam', 'Udung-Uko', 'Ukanafun', 'Uruan', 'Urue-Offong/Oruko', 'Uyo'],
            'Anambra' => [
                'Aguata',
                'Anambra East',
                'Anambra West',
                'Anaocha',
                'Awka North',
                'Awka South',
                'Ayamelum',
                'Dunukofia',
                'Ekwusigo',
                'Idemili North',
                'Idemili South',
                'Ihiala',
                'Njikoka',
                'Nnewi North',
                'Nnewi South',
                'Ogbaru',
                'Onitsha North',
                'Onitsha South',
                'Orumba North',
                'Orumba South',
                'Oyi'
            ],
            'Bauchi' => [
                'Alkaleri',
                'Bauchi',
                'Bogoro',
                'Damban',
                'Darazo',
                'Dass',
                'Gamawa',
                'Ganjuwa',
                'Giade',
                'Itas/Gadau',
                'Jama’are',
                'Katagum',
                'Kirfi',
                'Misau',
                'Ningi',
                'Shira',
                'Tafawa Balewa',
                'Toro',
                'Warji',
                'Zaki'
            ],
            'Bayelsa' => [
                'Brass',
                'Ekeremor',
                'Kolokuma/Opokuma',
                'Nembe',
                'Ogbia',
                'Sagbama',
                'Southern Ijaw',
                'Yenagoa'
            ],
            'Benue' => [
                'Ado',
                'Agatu',
                'Apa',
                'Buruku',
                'Gboko',
                'Guma',
                'Gwer East',
                'Gwer West',
                'Katsina-Ala',
                'Konshisha',
                'Kwande',
                'Logo',
                'Makurdi',
                'Obi',
                'Ogbadibo',
                'Ohimini',
                'Oju',
                'Okpokwu',
                'Otukpo',
                'Tarka',
                'Ukum',
                'Ushongo',
                'Vandeikya'
            ],
            'Borno' => [
                'Abadam',
                'Askira/Uba',
                'Bama',
                'Bayo',
                'Biu',
                'Chibok',
                'Damboa',
                'Dikwa',
                'Gubio',
                'Guzamala',
                'Gwoza',
                'Hawul',
                'Jere',
                'Kaga',
                'Kala/Balge',
                'Konduga',
                'Kukawa',
                'Kwaya Kusar',
                'Mafa',
                'Magumeri',
                'Maiduguri',
                'Marte',
                'Mobbar',
                'Monguno',
                'Ngala',
                'Nganzai',
                'Shani'
            ],
            'Cross River' => [
                'Abi',
                'Akamkpa',
                'Akpabuyo',
                'Bakassi',
                'Bekwarra',
                'Biase',
                'Boki',
                'Calabar Municipal',
                'Calabar South',
                'Etung',
                'Ikom',
                'Obanliku',
                'Obubra',
                'Obudu',
                'Odukpani',
                'Ogoja',
                'Yakurr',
                'Yala'
            ],

            'Delta' => [
                'Aniocha North',
                'Aniocha South',
                'Bomadi',
                'Burutu',
                'Ethiope East',
                'Ethiope West',
                'Ika North East',
                'Ika South',
                'Isoko North',
                'Isoko South',
                'Ndokwa East',
                'Ndokwa West',
                'Okpe',
                'Oshimili North',
                'Oshimili South',
                'Patani',
                'Sapele',
                'Udu',
                'Ughelli North',
                'Ughelli South',
                'Ukwuani',
                'Uvwie',
                'Warri North',
                'Warri South',
                'Warri South West'
            ],

            'Ebonyi' => [
                'Abakaliki',
                'Afikpo North',
                'Afikpo South',
                'Ebonyi',
                'Ezza North',
                'Ezza South',
                'Ikwo',
                'Ishielu',
                'Ivo',
                'Izzi',
                'Ohaozara',
                'Ohaukwu',
                'Onicha'
            ],

            'Edo' => [
                'Akoko-Edo',
                'Egor',
                'Esan Central',
                'Esan North-East',
                'Esan South-East',
                'Esan West',
                'Etsako Central',
                'Etsako East',
                'Etsako West',
                'Igueben',
                'Ikpoba-Okha',
                'Oredo',
                'Orhionmwon',
                'Ovia North-East',
                'Ovia South-West',
                'Owan East',
                'Owan West',
                'Uhunmwonde'
            ],

            'Ekiti' => [
                'Ado Ekiti',
                'Efon',
                'Ekiti East',
                'Ekiti South-West',
                'Ekiti West',
                'Emure',
                'Gbonyin',
                'Ido-Osi',
                'Ijero',
                'Ikere',
                'Ikole',
                'Ilejemeje',
                'Irepodun/Ifelodun',
                'Ise/Orun',
                'Moba',
                'Oye'
            ],

            'Enugu' => [
                'Aninri',
                'Awgu',
                'Enugu East',
                'Enugu North',
                'Enugu South',
                'Ezeagu',
                'Igbo Etiti',
                'Igbo Eze North',
                'Igbo Eze South',
                'Isi Uzo',
                'Nkanu East',
                'Nkanu West',
                'Nsukka',
                'Oji River',
                'Udenu',
                'Udi',
                'Uzo Uwani'
            ],
            'Gombe' => [
                'Akko',
                'Balanga',
                'Billiri',
                'Dukku',
                'Funakaye',
                'Gombe',
                'Kaltungo',
                'Kwami',
                'Nafada',
                'Shongom',
                'Yamaltu/Deba'
            ],

            'Imo' => [
                'Aboh Mbaise',
                'Ahiazu Mbaise',
                'Ehime Mbano',
                'Ezinihitte',
                'Ideato North',
                'Ideato South',
                'Ihitte/Uboma',
                'Ikeduru',
                'Isiala Mbano',
                'Isu',
                'Mbaitoli',
                'Ngor Okpala',
                'Njaba',
                'Nkwerre',
                'Nwangele',
                'Obowo',
                'Oguta',
                'Ohaji/Egbema',
                'Okigwe',
                'Orlu',
                'Orsu',
                'Oru East',
                'Oru West',
                'Owerri Municipal',
                'Owerri North',
                'Owerri West'
            ],

            'Jigawa' => [
                'Auyo',
                'Babura',
                'Biriniwa',
                'Birnin Kudu',
                'Buji',
                'Dutse',
                'Gagarawa',
                'Garki',
                'Gumel',
                'Guri',
                'Gwaram',
                'Gwiwa',
                'Hadejia',
                'Jahun',
                'Kafin Hausa',
                'Kaugama',
                'Kazaure',
                'Kiri Kasama',
                'Kiyawa',
                'Maigatari',
                'Malam Madori',
                'Miga',
                'Ringim',
                'Roni',
                'Sule Tankarkar',
                'Taura',
                'Yankwashi'
            ],

            'Kaduna' => [
                'Birnin Gwari',
                'Chikun',
                'Giwa',
                'Igabi',
                'Ikara',
                'Jaba',
                'Jema’a',
                'Kachia',
                'Kaduna North',
                'Kaduna South',
                'Kagarko',
                'Kajuru',
                'Kaura',
                'Kauru',
                'Kubau',
                'Kudan',
                'Lere',
                'Makarfi',
                'Sabon Gari',
                'Sanga',
                'Soba',
                'Zangon Kataf',
                'Zaria'
            ],

            'Kano' => [
                'Ajingi',
                'Albasu',
                'Bagwai',
                'Bebeji',
                'Bichi',
                'Bunkure',
                'Dala',
                'Dambatta',
                'Dawakin Kudu',
                'Dawakin Tofa',
                'Doguwa',
                'Fagge',
                'Gabasawa',
                'Garko',
                'Garun Mallam',
                'Gaya',
                'Gezawa',
                'Gwale',
                'Gwarzo',
                'Kabo',
                'Kano Municipal',
                'Karaye',
                'Kibiya',
                'Kiru',
                'Kumbotso',
                'Kunchi',
                'Kura',
                'Madobi',
                'Makoda',
                'Minjibir',
                'Nasarawa',
                'Rano',
                'Rimin Gado',
                'Rogo',
                'Shanono',
                'Sumaila',
                'Takai',
                'Tarauni',
                'Tofa',
                'Tsanyawa',
                'Tudun Wada',
                'Ungogo',
                'Warawa',
                'Wudil'
            ],

            'Katsina' => [
                'Bakori',
                'Batagarawa',
                'Batsari',
                'Baure',
                'Bindawa',
                'Charanchi',
                'Dandume',
                'Danja',
                'Dan Musa',
                'Daura',
                'Dutsi',
                'Dutsin Ma',
                'Faskari',
                'Funtua',
                'Ingawa',
                'Jibia',
                'Kafur',
                'Kaita',
                'Kankara',
                'Kankia',
                'Katsina',
                'Kurfi',
                'Kusada',
                'Mai\'Adua',
                'Malumfashi',
                'Mani',
                'Mashi',
                'Matazu',
                'Musawa',
                'Rimi',
                'Sabuwa',
                'Safana',
                'Sandamu',
                'Zango'
            ],

            'Kebbi' => [
                'Aleiro',
                'Arewa Dandi',
                'Argungu',
                'Augie',
                'Bagudo',
                'Birnin Kebbi',
                'Bunza',
                'Dandi',
                'Fakai',
                'Gwandu',
                'Jega',
                'Kalgo',
                'Koko/Besse',
                'Maiyama',
                'Ngaski',
                'Sakaba',
                'Shanga',
                'Suru',
                'Wasagu/Danko',
                'Yauri',
                'Zuru'
            ],

            'Kogi' => [
                'Adavi',
                'Ajaokuta',
                'Ankpa',
                'Bassa',
                'Dekina',
                'Ibaji',
                'Idah',
                'Igalamela-Odolu',
                'Ijumu',
                'Kabba/Bunu',
                'Kogi',
                'Lokoja',
                'Mopa-Muro',
                'Ofu',
                'Ogori/Magongo',
                'Okehi',
                'Okene',
                'Olamaboro',
                'Omala',
                'Yagba East',
                'Yagba West'
            ],
            'FCT' => ['Abaji', 'Bwari', 'Gwagwalada', 'Kuje', 'Kwali', 'Municipal Area Council']
        ];

        $now = Carbon::now();

        foreach ($statesWithLgas as $state => $lgas) {
            $stateRecord = DB::table('states')->where('name', $state)->first();

            if ($stateRecord) {
                foreach ($lgas as $lga) {
                    DB::table('lgas')->updateOrInsert(
                        ['state_id' => $stateRecord->id, 'name' => $lga],
                        ['created_at' => $now, 'updated_at' => $now]
                    );
                }
            }
        }
    }
}
